# Workflow for https://github.com/forgeglobal/shagorex/tree/development/github_actions/ensure-new-feature-flags-are-done-in-launch-darkly/
# Sample taken from: https://github.com/forgeglobal/shagorex/tree/development/github_actions/ensure-new-feature-flags-are-done-in-launch-darkly/ensure-new-feature-flags-are-done-in-launch-darkly.yml

name: Remove Heroku Feature Flags 

on:
  repository_dispatch:
    types: 
    - heroku-webhook-repository-trigger-release

jobs:  
  build:
    runs-on: ubuntu-latest
    name: Check and rerelease without disallowed Heroku feature flags
    # Update events come in after the create. This can get spammy for slack notifications, so only respond to release:create.
    if: ${{ github.event.client_payload.heroku_webhook.action == 'create' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: github_actions/ensure-new-feature-flags-are-done-in-launch-darkly/src
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Perform check and Heroku rerelease
       # Relative to root of github repo.
        run: BUNDLE_GEMFILE=github_actions/ensure-new-feature-flags-are-done-in-launch-darkly/src/Gemfile bundle exec ruby github_actions/ensure-new-feature-flags-are-done-in-launch-darkly/src/ensure_new_feature_flags_are_done_in_launch_darkly.rb
        
        env: # The following are example values. Make sure to fill in with what you need.
          HEROKU_API_KEY: ${{ secrets.NONPROD_HEROKU_API_KEY_FOR_HEROKU_EVENTS }}
          HEROKU_APP_ID: ${{ github.event.client_payload.heroku_webhook.data.app.id }}
          HEROKU_APP_NAME: ${{ github.event.client_payload.heroku_webhook.data.app.name }}
          HEROKU_RELEASE_ID: ${{ github.event.client_payload.heroku_webhook.data.id }}
          HEROKU_RELEASE_VERSION: ${{ github.event.client_payload.heroku_webhook.data.version }}
          FOR_HEROKU_PIPELINES: | 
            [
            ]
          FEATURE_FLAG_ALLOW_LIST: | 
            [
              "FEATURE_FLAG"
            ]
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,ref,workflow,job,github
          # Based on custom with fields feature: https://action-slack.netlify.app/usecase/02-custom
          custom_payload: |
            {
              attachments: [{
                color: 'danger',
                text: `<!channel> Disallowed feature flags have been added to Heroku app ${{ github.event.client_payload.heroku_webhook.data.app.name }}. <https://forgeglobal.atlassian.net/wiki/spaces/ENG/pages/2109276173/Adding+and+Managing+Flags+in+Launch+Darkly|Use Launch Darkly for feature flags.> See more details on the failure <https://github.com/ForgeRubenAguilar/integration-sandbox/actions/runs/${{ github.run_id }}|here.>`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_HEROKU_EVENTS }}
        if: ${{ failure() }}
          