A patch of meerkat hide, one tooth of a beluga whale, and a drop of blood from an overzealous dnd fanboy then...
Wait, that's all garnish. The recipe calls for marinated lamb baked for 8 mins at 400F.
