name: Test workflow

on:
  repository_dispatch:
    types: heroku-webhook-trigger
    
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run with input
    steps:
      - name: Output stuff
        run: "echo \"${{ JSON.stringify(github.event.client_payload) }}\""


