name: Test workflow

on:
  repository_dispatch:
    types: heroku-webhook-repository-trigger, heroku-webhook-fg-sharex-nonprod-ogg-trigger
    
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run with input
    steps:
      - name: Output stuff
        run: "echo \"${{ github.event.event_type }}\""


