name: Test workflow

on:
  repository_dispatch:
    types: 
    - not-real
    # - heroku-webhook-repository-trigger-release
    # - heroku-webhook-fg-sharex-nonprod-ogg-trigger-release
    
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run with input
    steps:
      - name: Output stuff
        run: "echo \"${{ github.event.event_type }}\""


